# Generated by Django 5.1.7 on 2025-03-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All_Rounder', 'All_Rounder'), ('Wicket_Keeper', 'Wicket_Keeper')], max_length=100)),
                ('country', models.CharField(choices=[('India', 'India'), ('Bangladesh', 'Bangladesh'), ('Sri_Lanka', 'Sri_Lanka'), ('Australia', 'Australia'), ('NewZeland', 'NewZeland'), ('England', 'England'), ('South_Africa', 'South_Africa'), ('West_Indies', 'West_Indies'), ('Other', 'Other')], max_length=100)),
                ('profile_pic', models.ImageField(upload_to='player/')),
                ('is_captain', models.BooleanField(default=False)),
                ('fav_food', models.ManyToManyField(to='crud.food')),
            ],
        ),
    ]
