# Generated by Django 5.1.7 on 2025-03-25 17:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
